# Generated by Django 4.1.7 on 2023-03-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=None, max_length=30)),
                ('fecha', models.DateTimeField(blank=None)),
                ('descripcion', models.TextField(blank=None, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='bombero',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
