# Generated by Django 4.1.7 on 2023-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_citacion_alter_bombero_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionEncuentroBriagada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cuerpo_bomberos', models.CharField(blank=None, max_length=30)),
                ('compañia', models.CharField(blank=None, max_length=30)),
                ('nombre_a_cargo', models.CharField(blank=None, max_length=30)),
                ('telefono', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('documento', models.FileField(upload_to='uploads/inscripciones_encuentro_brigadas/')),
            ],
        ),
    ]
