# Generated by Django 4.1.7 on 2023-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_inscripcionencuentrobriagada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InscripcionEncuentroBriagada',
            new_name='InscripcionEncuentroBrigada',
        ),
    ]
